# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0023_client_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='session',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='session',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userconsent',
            name='session',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
