# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0024_auto_20180202_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='backchannel_logout_uri',
            field=models.URLField(blank=True, help_text='If RP supports back channel logout, enter that uri here.', max_length=255, verbose_name='Back Channel Logout URI'),
        ),
    ]
